pre-commit:
  parallel: true
  commands:
    lint-staged:
      glob: "*.{js,ts,vue,mjs,json,md,yml,yaml}"
      run: bunx lint-staged

pre-push:
  commands:
    lint:
      run: bun run lint
    format-check:
      run: bun run format:check
