title: Filipe Crespo
description: >
  Sou Filipe Crespo, tenho 27 anos, nascido em Portugal e criado no Brasil.
  Já atuei em diversas áreas do mercado brasileiro de TI.
  Hoje sou desenvolvedor Php, Ruby e JavaScript, além disso me arrisco em projetos com Python, Node e VueJS.

permalink: /:categories/:title/
baseurl: ""
url: "https://filipecrespo.dev"

collections:
  my_collection:
    output: true
    permalink: /:collection/:name

site-twitter:
author: Filipe Crespo
author-img: filipe-crespo-avatar.png
social-twitter: filipecrespodev
social-facebook: filipecrespodev
social-github: filipecrespodev
social-linkedin: filipescrespo
social-twitch: filipecrespodev

analytics: UA-170278743-1

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jemoji

paginate: 10
paginate_path: "/page/:num"

lang: pt-BR
languages: ["pt"]

exclude: ["vender", "Dockerfile", "Docker-composer.yml", "LICENSE", "README.md"]
